-- Run this file in the Supabase SQL editor.
create table if not exists public.invoices (
  id text primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  invoice_number text not null check (char_length(invoice_number) between 1 and 80),
  customer_name text not null check (char_length(customer_name) between 1 and 200),
  customer_email text,
  customer_address text,
  issue_date date not null,
  due_date date not null,
  status text not null check (status in ('draft', 'sent', 'paid', 'overdue', 'cancelled')),
  currency text not null default 'CHF',
  items jsonb not null default '[]'::jsonb check (jsonb_typeof(items) = 'array'),
  notes text,
  paid_at date,
  created_at date not null,
  updated_at date not null,
  unique (user_id, invoice_number)
);

create table if not exists public.documents (
  id text primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  name text not null check (char_length(name) between 1 and 200),
  type text not null default 'receipt',
  document_date date not null,
  description text,
  file_name text,
  storage_path text,
  file_type text,
  file_size bigint,
  created_at date not null
);

create table if not exists public.expenses (
  id text primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  vendor text not null check (char_length(vendor) between 1 and 200),
  description text not null check (char_length(description) between 1 and 500),
  category text not null default 'other',
  amount numeric(12,2) not null check (amount >= 0),
  vat_amount numeric(12,2) not null default 0,
  currency text not null default 'CHF',
  expense_date date not null,
  payment_method text,
  document_id text references public.documents(id) on delete set null,
  is_recurring boolean not null default false,
  recurring_interval text check (recurring_interval in ('monthly', 'yearly')),
  recurring_start_date date,
  recurring_end_date date,
  created_at date not null,
  updated_at date not null
);

alter table public.documents alter column type set default 'receipt';
alter table public.expenses alter column category set default 'other';
alter table public.expenses alter column vat_amount set default 0;
alter table public.expenses add column if not exists is_recurring boolean not null default false;
alter table public.expenses add column if not exists recurring_interval text;
alter table public.expenses add column if not exists recurring_start_date date;
alter table public.expenses add column if not exists recurring_end_date date;

create table if not exists public.company_profiles (
  id text primary key,
  user_id uuid not null unique references auth.users(id) on delete cascade,
  company_name text not null check (char_length(company_name) between 1 and 200),
  owner_name text not null,
  email text not null,
  phone text,
  address text,
  postal_code text,
  city text,
  country text not null default 'Schweiz',
  website text,
  vat_number text,
  iban text,
  default_currency text not null default 'CHF',
  default_vat_rate numeric(5,2) not null default 0
);

create table if not exists public.customers (
  id text primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  company_name text not null check (char_length(company_name) between 1 and 200),
  contact_name text,
  email text,
  phone text,
  address text,
  project text,
  monthly_revenue numeric(12,2) not null default 0 check (monthly_revenue >= 0),
  one_time_revenue numeric(12,2) not null default 0 check (one_time_revenue >= 0),
  notes text,
  logo_path text,
  created_at date not null,
  updated_at date not null
);

alter table public.customers add column if not exists monthly_revenue numeric(12,2) not null default 0;
alter table public.customers add column if not exists one_time_revenue numeric(12,2) not null default 0;
alter table public.customers add column if not exists logo_path text;

create table if not exists public.prospects (
  id text primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  company_name text not null,
  contact_name text,
  email text,
  phone text,
  source text,
  status text not null check (status in ('new', 'contacted', 'meeting', 'offer', 'won', 'lost')),
  last_contact_at date,
  next_task text,
  next_task_at date,
  estimated_value numeric(12,2) check (estimated_value >= 0),
  notes text,
  created_at date not null,
  updated_at date not null
);

create table if not exists public.push_subscriptions (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  endpoint text not null,
  p256dh text not null,
  auth text not null,
  created_at timestamptz not null default now(),
  unique (user_id, endpoint)
);

create table if not exists public.push_deliveries (
  id bigint generated by default as identity primary key,
  subscription_id bigint not null references public.push_subscriptions(id) on delete cascade,
  item_id text not null,
  sent_on date not null default current_date,
  created_at timestamptz not null default now(),
  unique (subscription_id, item_id, sent_on)
);

create table if not exists public.workspace_items (
  id text primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  module text not null check (module in ('projects', 'ideas', 'tasks', 'offers', 'people', 'commissions', 'leads', 'operations')),
  title text not null check (char_length(title) between 1 and 200),
  subtitle text,
  description text,
  status text not null,
  priority text not null default 'medium' check (priority in ('low', 'medium', 'high')),
  owner text,
  contact_name text,
  email text,
  phone text,
  amount numeric(12,2) check (amount is null or amount >= 0),
  start_date date,
  due_date date,
  tags text[] not null default '{}',
  created_at date not null,
  updated_at date not null
);

create table if not exists public.workspace_files (
  id text primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  item_id text not null references public.workspace_items(id) on delete cascade,
  name text not null,
  storage_path text not null unique,
  file_type text,
  file_size bigint,
  created_at date not null
);

create table if not exists public.monthly_goals (
  id text primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  month text not null check (month ~ '^\d{4}-(0[1-9]|1[0-2])$'),
  revenue_target numeric(12,2) not null default 0 check (revenue_target >= 0),
  recurring_revenue_target numeric(12,2) not null default 0 check (recurring_revenue_target >= 0),
  expense_budget numeric(12,2) not null default 0 check (expense_budget >= 0),
  notes text,
  created_at date not null,
  updated_at date not null,
  unique (user_id, month)
);

create table if not exists public.todos (
  id text primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  title text not null check (char_length(title) between 1 and 200),
  notes text,
  status text not null default 'not_started' check (status in ('not_started', 'in_progress', 'done')),
  due_date date,
  customer_id text references public.customers(id) on delete set null,
  prospect_id text references public.prospects(id) on delete set null,
  created_at date not null,
  updated_at date not null
);

create table if not exists public.todo_comments (
  id text primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  todo_id text not null references public.todos(id) on delete cascade,
  body text not null check (char_length(body) between 1 and 2000),
  created_at timestamptz not null default now()
);

alter table public.invoices enable row level security;
alter table public.expenses enable row level security;
alter table public.documents enable row level security;
alter table public.company_profiles enable row level security;
alter table public.customers enable row level security;
alter table public.prospects enable row level security;
alter table public.push_subscriptions enable row level security;
alter table public.push_deliveries enable row level security;
alter table public.workspace_items enable row level security;
alter table public.workspace_files enable row level security;
alter table public.monthly_goals enable row level security;
alter table public.todos enable row level security;
alter table public.todo_comments enable row level security;

drop policy if exists "users manage own invoices" on public.invoices;
drop policy if exists "users manage own expenses" on public.expenses;
drop policy if exists "users manage own documents" on public.documents;
drop policy if exists "users manage own company profile" on public.company_profiles;
drop policy if exists "users manage own customers" on public.customers;
drop policy if exists "users manage own prospects" on public.prospects;
drop policy if exists "users manage own push subscriptions" on public.push_subscriptions;
drop policy if exists "users manage own workspace items" on public.workspace_items;
drop policy if exists "users manage own workspace files" on public.workspace_files;
drop policy if exists "users manage own monthly goals" on public.monthly_goals;
drop policy if exists "users manage own todos" on public.todos;
drop policy if exists "users manage own todo comments" on public.todo_comments;
create policy "users manage own invoices" on public.invoices for all to authenticated using (auth.uid() = user_id) with check (auth.uid() = user_id);
create policy "users manage own expenses" on public.expenses for all to authenticated using (auth.uid() = user_id) with check (auth.uid() = user_id);
create policy "users manage own documents" on public.documents for all to authenticated using (auth.uid() = user_id) with check (auth.uid() = user_id);
create policy "users manage own company profile" on public.company_profiles for all to authenticated using (auth.uid() = user_id) with check (auth.uid() = user_id);
create policy "users manage own customers" on public.customers for all to authenticated using (auth.uid() = user_id) with check (auth.uid() = user_id);
create policy "users manage own prospects" on public.prospects for all to authenticated using (auth.uid() = user_id) with check (auth.uid() = user_id);
create policy "users manage own push subscriptions" on public.push_subscriptions for all to authenticated using (auth.uid() = user_id) with check (auth.uid() = user_id);
create policy "users manage own workspace items" on public.workspace_items for all to authenticated using (auth.uid() = user_id) with check (auth.uid() = user_id);
create policy "users manage own workspace files" on public.workspace_files for all to authenticated using (auth.uid() = user_id) with check (auth.uid() = user_id);
create policy "users manage own monthly goals" on public.monthly_goals for all to authenticated using (auth.uid() = user_id) with check (auth.uid() = user_id);
create policy "users manage own todos" on public.todos for all to authenticated using (auth.uid() = user_id) with check (auth.uid() = user_id);
create policy "users manage own todo comments" on public.todo_comments for all to authenticated using (auth.uid() = user_id) with check (auth.uid() = user_id);

insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values ('documents', 'documents', false, 10485760, array['application/pdf', 'image/png', 'image/jpeg', 'image/webp'])
on conflict (id) do update set public = false, file_size_limit = excluded.file_size_limit, allowed_mime_types = excluded.allowed_mime_types;
drop policy if exists "users manage own accounting documents" on storage.objects;
create policy "users manage own accounting documents" on storage.objects for all to authenticated
using (bucket_id = 'documents' and auth.uid()::text = (storage.foldername(name))[1])
with check (bucket_id = 'documents' and auth.uid()::text = (storage.foldername(name))[1]);

insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values ('workspace-files', 'workspace-files', false, 15728640, array['application/pdf', 'image/png', 'image/jpeg', 'image/webp', 'text/plain', 'application/vnd.openxmlformats-officedocument.wordprocessingml.document', 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet'])
on conflict (id) do update set public = false, file_size_limit = excluded.file_size_limit, allowed_mime_types = excluded.allowed_mime_types;
drop policy if exists "users manage own workspace objects" on storage.objects;
create policy "users manage own workspace objects" on storage.objects for all to authenticated
using (bucket_id = 'workspace-files' and auth.uid()::text = (storage.foldername(name))[1])
with check (bucket_id = 'workspace-files' and auth.uid()::text = (storage.foldername(name))[1]);

insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values ('customer-logos', 'customer-logos', true, 2097152, array['image/png', 'image/jpeg', 'image/webp'])
on conflict (id) do update set public = true, file_size_limit = excluded.file_size_limit, allowed_mime_types = excluded.allowed_mime_types;
drop policy if exists "public can view customer logos" on storage.objects;
create policy "public can view customer logos" on storage.objects for select to public
using (bucket_id = 'customer-logos');
drop policy if exists "users manage own customer logos" on storage.objects;
create policy "users manage own customer logos" on storage.objects for all to authenticated
using (bucket_id = 'customer-logos' and auth.uid()::text = (storage.foldername(name))[1])
with check (bucket_id = 'customer-logos' and auth.uid()::text = (storage.foldername(name))[1]);

drop function if exists public.is_app_member();

create index if not exists invoices_user_issue_date_idx on public.invoices (user_id, issue_date desc);
create index if not exists expenses_user_expense_date_idx on public.expenses (user_id, expense_date desc);
create index if not exists documents_user_document_date_idx on public.documents (user_id, document_date desc);
create index if not exists customers_user_company_name_idx on public.customers (user_id, company_name);
create index if not exists prospects_user_updated_at_idx on public.prospects (user_id, updated_at desc);
create index if not exists push_subscriptions_user_id_idx on public.push_subscriptions (user_id);
create index if not exists push_deliveries_sent_on_idx on public.push_deliveries (sent_on);
create index if not exists workspace_items_user_module_idx on public.workspace_items (user_id, module, updated_at desc);
create index if not exists workspace_files_item_id_idx on public.workspace_files (item_id);
create index if not exists monthly_goals_user_month_idx on public.monthly_goals (user_id, month desc);
create index if not exists todos_user_due_date_idx on public.todos (user_id, due_date);
create index if not exists todos_user_status_idx on public.todos (user_id, status);
create index if not exists todo_comments_todo_id_idx on public.todo_comments (todo_id, created_at);

create or replace function public.valid_invoice_items(items jsonb)
returns boolean
language sql
immutable
set search_path = ''
as $$
  select jsonb_typeof(items) = 'array'
    and jsonb_array_length(items) > 0
    and not exists (
      select 1 from jsonb_array_elements(items) item
      where coalesce((item ->> 'quantity')::numeric, 0) <= 0
        or coalesce((item ->> 'unitPrice')::numeric, -1) < 0
        or coalesce((item ->> 'vatRate')::numeric, -1) not between 0 and 100
        or char_length(trim(coalesce(item ->> 'description', ''))) = 0
    );
$$;

alter table public.invoices drop constraint if exists invoices_items_valid;
alter table public.invoices add constraint invoices_items_valid check (public.valid_invoice_items(items)) not valid;

create or replace function public.due_notifications()
returns table (user_id uuid, item_id text, title text, body text, href text)
language sql
stable
security definer
set search_path = ''
as $$
  select i.user_id, 'invoice-' || i.id, 'Rechnung ' || i.invoice_number,
    i.customer_name || ' · fällig ' || to_char(i.due_date, 'DD.MM.YYYY'), '/applications/' || i.id
  from public.invoices i
  where i.status in ('sent', 'overdue') and i.due_date <= current_date
  union all
  select p.user_id, 'prospect-' || p.id, p.next_task,
    p.company_name || ' · fällig ' || to_char(p.next_task_at, 'DD.MM.YYYY'), '/prospects'
  from public.prospects p
  where p.next_task is not null and p.next_task_at <= current_date and p.status not in ('won', 'lost')
  union all
  select w.user_id, 'workspace-' || w.id, w.title,
    initcap(w.module) || ' · fällig ' || to_char(w.due_date, 'DD.MM.YYYY'), '/workspace/' || w.module
  from public.workspace_items w
  where w.due_date <= current_date and w.status not in ('Erledigt', 'Abgeschlossen', 'Bezahlt', 'Gewonnen', 'Archiviert', 'Angenommen', 'Abgelehnt', 'Verloren', 'Storniert', 'Ehemalig')
  union all
  select t.user_id, 'todo-' || t.id, t.title,
    'To-Do · fällig ' || to_char(t.due_date, 'DD.MM.YYYY'), '/todos'
  from public.todos t
  where t.due_date is not null and t.due_date <= current_date and t.status <> 'done';
$$;

revoke all on function public.due_notifications() from public, anon, authenticated;
grant execute on function public.due_notifications() to service_role;
