"use client";

import { useEffect, useRef, useState } from "react";
import { Eye, FileArchive } from "lucide-react";
import { WorkspaceShell } from "@/components/layout/workspace-shell";
import { getDocuments, getDocumentUrl, uploadDocument } from "@/lib/storage";
import type { Document } from "@/types";

export default function DocumentsPage() {
  const [documents, setDocuments] = useState<Document[]>([]); const [notice, setNotice] = useState(""); const [busy, setBusy] = useState(false); const fileRef = useRef<HTMLInputElement>(null); const [form, setForm] = useState({ name: "", documentDate: new Date().toISOString().slice(0, 10) });
  useEffect(() => { getDocuments().then(setDocuments).catch((cause) => setNotice(cause instanceof Error ? cause.message : "Belege konnten nicht geladen werden.")); }, []);
  async function upload(file?: File) { if (!file || !form.name) { setNotice("Bitte Bezeichnung und Datei angeben."); return; } setBusy(true); try { const document = await uploadDocument(form, file); setDocuments((current) => [document, ...current]); setForm((current) => ({ ...current, name: "" })); setNotice("Beleg gespeichert."); if (fileRef.current) fileRef.current.value = ""; } catch (cause) { setNotice(cause instanceof Error ? cause.message : "Upload fehlgeschlagen."); } finally { setBusy(false); } }
  async function preview(document: Document) { if (document.storagePath) window.open(await getDocumentUrl(document.storagePath), "_blank", "noopener,noreferrer"); }
  return <WorkspaceShell active="Belege" title="Wendico / Belege"><div><p className="text-xs font-semibold uppercase tracking-[.18em] text-[#56c8ff]">Ablage</p><h1 className="mt-3 text-3xl font-semibold text-white">Belege</h1><p className="mt-2 text-sm text-[#8292ae]">Geschäftliche Belege einfach hochladen und wiederfinden.</p></div>{notice && <div className="mt-5 rounded-xl border border-[#2d79b7] bg-[#0b2948] px-4 py-3 text-sm text-[#8edaff]">{notice}</div>}<section className="panel mt-8 grid gap-4 rounded-2xl p-5 md:grid-cols-3"><Field label="Bezeichnung" value={form.name} onChange={(value) => setForm({ ...form, name: value })}/><Field label="Datum" type="date" value={form.documentDate} onChange={(value) => setForm({ ...form, documentDate: value })}/><label><span className="mb-2 block text-xs text-[#8292ae]">Datei</span><input ref={fileRef} type="file" accept=".pdf,.png,.jpg,.jpeg,.webp" disabled={busy} onChange={(event) => upload(event.target.files?.[0])} className="block w-full text-xs text-[#8292ae] file:mr-3 file:rounded-lg file:border-0 file:bg-[#153a71] file:px-3 file:py-2.5 file:text-[#8edaff]"/></label></section><div className="mt-6 grid gap-4 sm:grid-cols-2 xl:grid-cols-3">{documents.map((document) => <article key={document.id} className="panel rounded-2xl p-5"><div className="flex h-11 w-11 items-center justify-center rounded-xl bg-[#102b56] text-[#62c8ff]"><FileArchive size={20}/></div><h2 className="mt-5 font-semibold text-white">{document.name}</h2><p className="mt-2 truncate text-xs text-[#7185a6]">{document.fileName}</p><p className="mt-2 text-xs text-[#7185a6]">{new Date(document.documentDate).toLocaleDateString("de-CH")}</p><button disabled={!document.storagePath} onClick={() => preview(document)} className="mt-5 flex items-center gap-2 text-sm text-[#65c6ff]"><Eye size={15}/>Ansehen</button></article>)}{!documents.length && <div className="panel col-span-full rounded-2xl py-14 text-center text-sm text-[#7185a6]">{busy ? "Beleg wird hochgeladen..." : "Noch keine Belege abgelegt."}</div>}</div></WorkspaceShell>;
}
function Field({ label, value, onChange, type = "text" }: { label: string; value: string; onChange: (value: string) => void; type?: string }) { return <label><span className="mb-2 block text-xs text-[#8292ae]">{label}</span><input type={type} value={value} onChange={(event) => onChange(event.target.value)} className="field"/></label>; }
