import { calculateMatchScore } from "@/lib/match-score";
import { supabase } from "@/lib/supabase";
import type { Application, CV, Profile } from "@/types";

type ApplicationRow = Omit<Application, "jobUrl" | "salaryMin" | "salaryMax" | "matchScore" | "appliedAt" | "createdAt" | "updatedAt" | "jobDescription" | "cvType"> & { user_id: string; job_url?: string; salary_min?: number; salary_max?: number; match_score?: number; applied_at?: string; created_at: string; updated_at: string; job_description?: string; cv_type?: Application["cvType"] };

async function currentUserId() { const { data, error } = await supabase.auth.getUser(); if (error || !data.user) throw new Error("You must be signed in."); return data.user.id; }
function databaseError(error: { code?: string; message?: string; details?: string | null; hint?: string | null }) { const parts = [error.code, error.message, error.details, error.hint].filter(Boolean); return new Error(`Database error: ${parts.join(" | ")}`); }

function fromRow(row: ApplicationRow): Application { return { id: row.id, company: row.company, position: row.position, location: row.location, jobUrl: row.job_url, source: row.source, category: row.category, salaryMin: row.salary_min, salaryMax: row.salary_max, currency: row.currency, deadline: row.deadline, status: row.status, matchScore: row.match_score, appliedAt: row.applied_at, createdAt: row.created_at, updatedAt: row.updated_at, cvType: row.cv_type, jobDescription: row.job_description, notes: row.notes }; }
function toRow(application: Application, userId: string): ApplicationRow { return { user_id: userId, id: application.id, company: application.company, position: application.position, location: application.location || undefined, job_url: application.jobUrl || undefined, source: application.source || undefined, category: application.category, salary_min: application.salaryMin, salary_max: application.salaryMax, currency: application.currency || undefined, deadline: application.deadline || undefined, status: application.status, match_score: application.matchScore, applied_at: application.appliedAt || undefined, created_at: application.createdAt, updated_at: application.updatedAt, cv_type: application.cvType, job_description: application.jobDescription || undefined, notes: application.notes || undefined }; }

export async function getApplications(): Promise<Application[]> { const userId = await currentUserId(); const { data, error } = await supabase.from("applications").select("*").eq("user_id", userId).order("updated_at", { ascending: false }); if (error) throw error; return (data as ApplicationRow[] | null ?? []).map(fromRow); }
export async function getApplication(id: string) { const userId = await currentUserId(); const { data, error } = await supabase.from("applications").select("*").eq("id", id).eq("user_id", userId).maybeSingle(); if (error) throw error; return data ? fromRow(data as ApplicationRow) : undefined; }
export async function createApplication(input: Omit<Application, "id" | "createdAt" | "updatedAt">) { const userId = await currentUserId(); const now = new Date().toISOString().slice(0, 10); const application: Application = { ...input, matchScore: calculateMatchScore(input), id: `${userId}-app-${Date.now()}`, createdAt: now, updatedAt: now }; const { error } = await supabase.from("applications").insert(toRow(application, userId)); if (error) throw databaseError(error); return application; }
export async function updateApplication(id: string, changes: Partial<Application>) { const userId = await currentUserId(); const current = await getApplication(id); if (!current) return undefined; const merged = { ...current, ...changes }; const updated: Application = { ...merged, matchScore: calculateMatchScore(merged), updatedAt: new Date().toISOString().slice(0, 10) }; const { error } = await supabase.from("applications").update(toRow(updated, userId)).eq("id", id).eq("user_id", userId); if (error) throw error; return updated; }
export async function deleteApplication(id: string) { const userId = await currentUserId(); const { error } = await supabase.from("applications").delete().eq("id", id).eq("user_id", userId); if (error) throw error; }
export async function importApplications(applications: Application[]) { const userId = await currentUserId(); const { error } = await supabase.from("applications").upsert(applications.map((application) => toRow(application, userId))); if (error) throw error; }

export async function getProfile(): Promise<Profile> { const userId = await currentUserId(); const { data, error } = await supabase.from("profiles").select("*").eq("user_id", userId).maybeSingle(); if (error) throw error; if (!data) return { firstName: "", lastName: "", email: "", phone: "", location: "", website: "", linkedIn: "" }; return { firstName: data.first_name, lastName: data.last_name, email: data.email, phone: data.phone, location: data.location, website: data.website, linkedIn: data.linkedin }; }
export async function saveProfile(profile: Profile) { const userId = await currentUserId(); const { error } = await supabase.from("profiles").upsert({ id: `profile-${userId}`, user_id: userId, first_name: profile.firstName, last_name: profile.lastName, email: profile.email, phone: profile.phone, location: profile.location, website: profile.website, linkedin: profile.linkedIn }); if (error) throw error; }
export async function getCVs(): Promise<CV[]> { const userId = await currentUserId(); const { data, error } = await supabase.from("cvs").select("*").eq("user_id", userId).order("updated_at", { ascending: false }); if (error) throw error; return (data ?? []).map((cv) => ({ id: cv.id, name: cv.name, type: cv.type, description: cv.description, updatedAt: cv.updated_at, status: cv.status })); }
export async function updateCV(id: string, changes: Partial<CV>) { const userId = await currentUserId(); const { data, error } = await supabase.from("cvs").update({ name: changes.name, type: changes.type, description: changes.description, status: changes.status, updated_at: new Date().toISOString().slice(0, 10), file_name: changes.fileName, file_type: changes.fileType, file_size: changes.fileSize, storage_path: changes.storagePath }).eq("id", id).eq("user_id", userId).select("*").single(); if (error) throw databaseError(error); return { id: data.id, name: data.name, type: data.type, description: data.description, updatedAt: data.updated_at, status: data.status, fileName: data.file_name, fileType: data.file_type, fileSize: data.file_size, storagePath: data.storage_path } as CV; }
export async function uploadCV(id: string, file: File) { const userId = await currentUserId(); const path = `${userId}/${id}/${file.name}`; const { error: uploadError } = await supabase.storage.from("cvs").upload(path, file, { upsert: true, contentType: file.type || "application/octet-stream" }); if (uploadError) throw databaseError(uploadError); return updateCV(id, { fileName: file.name, fileType: file.type, fileSize: file.size, storagePath: path, status: "Ready" }); }
export async function getCVPreviewUrl(path: string) { const { data, error } = await supabase.storage.from("cvs").createSignedUrl(path, 60 * 10); if (error) throw databaseError(error); return data.signedUrl; }
export async function clearLocalData() { const userId = await currentUserId(); const [applications, profile, cvs] = await Promise.all([supabase.from("applications").delete().eq("user_id", userId), supabase.from("profiles").delete().eq("user_id", userId), supabase.from("cvs").delete().eq("user_id", userId)]); const error = applications.error ?? profile.error ?? cvs.error; if (error) throw error; }
