"use client";

import { useState } from "react";
import { useRouter } from "next/navigation";
import { createApplication, updateApplication } from "@/lib/storage";
import type { Application, ApplicationCategory, ApplicationStatus } from "@/types";

const categoryValues: ApplicationCategory[] = ["software", "sales", "business", "finance", "banking", "consulting", "other"];
const statusValues: ApplicationStatus[] = ["saved", "preparing", "applied", "interview", "final_interview", "offer", "rejected", "withdrawn"];
const categoryLabels: Record<ApplicationCategory, string> = { software: "Software", sales: "Vertrieb", business: "Business", finance: "Finanzen", banking: "Banking", consulting: "Beratung", other: "Sonstiges" };
const statusLabels: Record<ApplicationStatus, string> = { saved: "Gespeichert", preparing: "In Vorbereitung", applied: "Beworben", interview: "Vorstellungsgespräch", final_interview: "Finales Gespräch", offer: "Angebot", rejected: "Abgelehnt", withdrawn: "Zurückgezogen" };
const categories = categoryValues.map((value) => ({ value, label: categoryLabels[value] }));
const statuses = statusValues.map((value) => ({ value, label: statusLabels[value] }));

type FormValue = { company: string; position: string; location: string; jobUrl: string; source: string; category: ApplicationCategory; salaryMin: string; salaryMax: string; currency: string; deadline: string; status: ApplicationStatus; jobDescription: string; notes: string };
const blankForm: FormValue = { company: "", position: "", location: "", jobUrl: "", source: "", category: "software", salaryMin: "", salaryMax: "", currency: "CHF", deadline: "", status: "saved", jobDescription: "", notes: "" };

function toForm(application?: Application): FormValue { return application ? { company: application.company, position: application.position, location: application.location ?? "", jobUrl: application.jobUrl ?? "", source: application.source ?? "", category: application.category, salaryMin: application.salaryMin?.toString() ?? "", salaryMax: application.salaryMax?.toString() ?? "", currency: application.currency ?? "CHF", deadline: application.deadline ?? "", status: application.status, jobDescription: application.jobDescription ?? "", notes: application.notes ?? "" } : blankForm; }

export function ApplicationForm({ application }: { application?: Application }) {
  const router = useRouter();
  const [form, setForm] = useState<FormValue>(() => toForm(application));
  const [saving, setSaving] = useState(false);
  const [error, setError] = useState("");
  const isEditing = Boolean(application);
  const update = (key: keyof FormValue, value: string) => setForm((current) => ({ ...current, [key]: value }));
  async function submit(event: React.FormEvent<HTMLFormElement>) {
    event.preventDefault(); setSaving(true); setError("");
    const payload = { ...form, salaryMin: form.salaryMin ? Number(form.salaryMin) : undefined, salaryMax: form.salaryMax ? Number(form.salaryMax) : undefined, appliedAt: ["applied", "interview", "final_interview", "offer", "rejected"].includes(form.status) ? (application?.appliedAt ?? new Date().toISOString().slice(0, 10)) : undefined };
    try { const result = isEditing && application ? await updateApplication(application.id, payload) : await createApplication(payload); if (result) router.push(`/applications/${result.id}`); } catch (cause) { setError(cause instanceof Error ? cause.message : "Could not save this application."); setSaving(false); }
  }
  return <form onSubmit={submit} className="space-y-6">{error && <div role="alert" className="rounded-xl border border-[#6e3340] bg-[#24131e] px-4 py-3 text-sm text-[#ffaaa0]">{error}</div>}<div className="grid gap-4 sm:grid-cols-2"><Field label="Company" required value={form.company} onChange={(value) => update("company", value)} placeholder="e.g. Swisscom" /><Field label="Position" required value={form.position} onChange={(value) => update("position", value)} placeholder="e.g. Product Designer" /><Field label="Location" value={form.location} onChange={(value) => update("location", value)} placeholder="Zürich, hybrid" /><Field label="Job URL" value={form.jobUrl} onChange={(value) => update("jobUrl", value)} placeholder="https://..." type="url" /><Field label="Source" value={form.source} onChange={(value) => update("source", value)} placeholder="LinkedIn, referral..." /><SelectField label="Category" value={form.category} onChange={(value) => update("category", value)} options={categories} /><SelectField label="Status" value={form.status} onChange={(value) => update("status", value)} options={statuses} /><Field label="Deadline" value={form.deadline} onChange={(value) => update("deadline", value)} type="date" /></div><div className="grid gap-4 sm:grid-cols-3"><Field label="Salary min" value={form.salaryMin} onChange={(value) => update("salaryMin", value)} type="number" placeholder="70000" /><Field label="Salary max" value={form.salaryMax} onChange={(value) => update("salaryMax", value)} type="number" placeholder="90000" /><Field label="Currency" value={form.currency} onChange={(value) => update("currency", value)} placeholder="CHF" /></div><div className="grid gap-4 sm:grid-cols-2"><TextArea label="Job description" value={form.jobDescription} onChange={(value) => update("jobDescription", value)} placeholder="Paste the role description here..." /><TextArea label="Notes" value={form.notes} onChange={(value) => update("notes", value)} placeholder="What stands out about this opportunity?" /></div><div className="flex items-center justify-end gap-3 border-t border-white/10 pt-5"><button type="button" onClick={() => router.back()} className="rounded-xl px-4 py-2.5 text-sm font-medium text-[#8292ae] hover:text-white">Cancel</button><button disabled={saving} className="rounded-xl bg-gradient-to-r from-[#328dff] to-[#55c9ff] px-5 py-2.5 text-sm font-semibold text-[#061022] disabled:opacity-60">{saving ? "Saving..." : isEditing ? "Save changes" : "Create application"}</button></div></form>;
}

function Field({ label, value, onChange, placeholder, type = "text", required = false }: { label: string; value: string; onChange: (value: string) => void; placeholder?: string; type?: string; required?: boolean }) { return <label className="block text-sm"><span className="mb-2 block text-xs font-semibold text-[#8292ae]">{label}{required && <span className="text-[#ff8f85]"> *</span>}</span><input required={required} type={type} value={value} placeholder={placeholder} onChange={(event) => onChange(event.target.value)} className="w-full rounded-xl border border-white/10 bg-[#08172f] px-3.5 py-2.5 text-sm text-white outline-none transition placeholder:text-[#526b8c] focus:border-[#4ca6ff] focus:ring-2 focus:ring-[#163a68]" /></label>; }
function SelectField({ label, value, onChange, options }: { label: string; value: string; onChange: (value: string) => void; options: { value: string; label: string }[] }) { return <label className="block text-sm"><span className="mb-2 block text-xs font-semibold text-[#8292ae]">{label}</span><select value={value} onChange={(event) => onChange(event.target.value)} className="w-full rounded-xl border border-white/10 bg-[#08172f] px-3.5 py-2.5 text-sm text-white outline-none focus:border-[#4ca6ff]">{options.map((option) => <option key={option.value} value={option.value}>{option.label}</option>)}</select></label>; }
function TextArea({ label, value, onChange, placeholder }: { label: string; value: string; onChange: (value: string) => void; placeholder: string }) { return <label className="block text-sm"><span className="mb-2 block text-xs font-semibold text-[#8292ae]">{label}</span><textarea rows={6} value={value} placeholder={placeholder} onChange={(event) => onChange(event.target.value)} className="w-full resize-y rounded-xl border border-white/10 bg-[#08172f] px-3.5 py-2.5 text-sm text-white outline-none placeholder:text-[#526b8c] focus:border-[#4ca6ff] focus:ring-2 focus:ring-[#163a68]" /></label>; }
