"use client";

import { useEffect, useState } from "react";
import { Database, Download, Moon, ShieldCheck, Sun } from "lucide-react";
import { WorkspaceShell } from "@/components/layout/workspace-shell";
import { getAllWorkspaceItems, getCompanyProfile, getCustomers, getDocuments, getExpenses, getInvoices, getProspects, getWorkspaceFiles } from "@/lib/storage";

export default function SettingsPage() {
  const [notice, setNotice] = useState(""); const [lightMode, setLightMode] = useState(false);
  useEffect(() => { const update = () => setLightMode(document.documentElement.classList.contains("light")); update(); window.addEventListener("wendico-books-theme", update); return () => window.removeEventListener("wendico-books-theme", update); }, []);
  async function exportData() { const workspace = await getAllWorkspaceItems(); const payload = { invoices: await getInvoices(), expenses: await getExpenses(), documents: await getDocuments(), customers: await getCustomers(), prospects: await getProspects(), workspace, workspaceFiles: await getWorkspaceFiles(workspace.map((item) => item.id)), company: await getCompanyProfile(), exportedAt: new Date().toISOString() }; const url = URL.createObjectURL(new Blob([JSON.stringify(payload, null, 2)], { type: "application/json" })); const anchor = document.createElement("a"); anchor.href = url; anchor.download = `wendico-export-${new Date().toISOString().slice(0, 10)}.json`; anchor.click(); URL.revokeObjectURL(url); setNotice("Daten exportiert."); }
  function toggleTheme() { const next = lightMode ? "dark" : "light"; document.documentElement.classList.toggle("light", next === "light"); window.localStorage.setItem("wendico-books.theme", next); window.dispatchEvent(new CustomEvent("wendico-books-theme")); }
  return <WorkspaceShell active="Einstellungen" title="Wendico / Einstellungen"><div><p className="text-xs font-semibold uppercase tracking-[.18em] text-[#56c8ff]">System</p><h1 className="mt-3 text-3xl font-semibold text-white">Einstellungen</h1><p className="mt-2 text-sm text-[#8292ae]">Datensicherung, Darstellung und Zugriff.</p></div>{notice && <div className="mt-6 rounded-xl border border-[#2d79b7] bg-[#0b2948] px-4 py-3 text-sm text-[#8edaff]">{notice}</div>}<div className="mt-8 grid gap-5 lg:grid-cols-2"><Section icon={Database} title="Datensicherung" description="Lade eine Kopie aller Geschäfts- und Kontaktdaten herunter."><button onClick={exportData} className="action"><Download size={15}/>Daten exportieren</button></Section><Section icon={lightMode ? Sun : Moon} title="Darstellung" description="Wechsle zwischen heller und dunkler Oberfläche."><button onClick={toggleTheme} className="action">{lightMode ? <Moon size={15}/> : <Sun size={15}/>}Modus wechseln</button></Section><Section icon={ShieldCheck} title="Sicherheit" description="Supabase schützt den Zugriff auf eure Daten."><p className="text-sm text-[#8292ae]">Nur angemeldete Benutzer können die Daten sehen und bearbeiten.</p></Section></div></WorkspaceShell>;
}
function Section({ icon: Icon, title, description, children }: { icon: typeof Database; title: string; description: string; children: React.ReactNode }) { return <section className="panel rounded-2xl p-5"><div className="flex gap-3"><Icon size={18} className="mt-0.5 text-[#56c8ff]"/><div><h2 className="text-sm font-semibold text-white">{title}</h2><p className="mt-1 text-xs text-[#7185a6]">{description}</p><div className="mt-5">{children}</div></div></div></section>; }
