create table if not exists public.push_subscriptions (
	id bigint generated by default as identity primary key,
	user_id uuid not null references auth.users(id) on delete cascade,
	endpoint text not null,
	p256dh text not null,
	auth text not null,
	created_at timestamptz not null default now(),
	unique (user_id, endpoint)
);

create table if not exists public.push_deliveries (
	id bigint generated by default as identity primary key,
	subscription_id bigint not null references public.push_subscriptions(id) on delete cascade,
	item_id text not null,
	sent_on date not null default current_date,
	created_at timestamptz not null default now(),
	unique (subscription_id, item_id, sent_on)
);

alter table public.push_subscriptions enable row level security;
alter table public.push_deliveries enable row level security;

drop policy if exists "users manage own push subscriptions" on public.push_subscriptions;
create policy "users manage own push subscriptions" on public.push_subscriptions
for all to authenticated using (auth.uid() = user_id) with check (auth.uid() = user_id);

insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values ('documents', 'documents', false, 10485760, array['application/pdf', 'image/png', 'image/jpeg', 'image/webp'])
on conflict (id) do update set public = false, file_size_limit = excluded.file_size_limit, allowed_mime_types = excluded.allowed_mime_types;

create index if not exists push_subscriptions_user_id_idx on public.push_subscriptions (user_id);
create index if not exists push_deliveries_sent_on_idx on public.push_deliveries (sent_on);

create or replace function public.due_notifications()
returns table (user_id uuid, item_id text, title text, body text, href text)
language sql
stable
security definer
set search_path = ''
as $$
	select i.user_id, 'invoice-' || i.id, 'Rechnung ' || i.invoice_number,
		i.customer_name || ' · fällig ' || to_char(i.due_date, 'DD.MM.YYYY'), '/applications/' || i.id
	from public.invoices i
	where i.status in ('sent', 'overdue') and i.due_date <= current_date
	union all
	select p.user_id, 'prospect-' || p.id, p.next_task,
		p.company_name || ' · fällig ' || to_char(p.next_task_at, 'DD.MM.YYYY'), '/prospects'
	from public.prospects p
	where p.next_task is not null and p.next_task_at <= current_date and p.status not in ('won', 'lost');
$$;

revoke all on function public.due_notifications() from public, anon, authenticated;
grant execute on function public.due_notifications() to service_role;
