"use client";

import { useEffect, useState } from "react";
import Link from "next/link";
import { useParams, useRouter } from "next/navigation";
import { ArrowLeft, Pencil, Trash2 } from "lucide-react";
import { ApplicationForm } from "@/components/applications/application-form";
import { WorkspaceShell } from "@/components/layout/workspace-shell";
import { deleteInvoice, getInvoice, updateInvoice } from "@/lib/storage";
import { formatCurrency, invoiceStatusLabels, invoiceTotal } from "@/lib/utils";
import type { Invoice, InvoiceStatus } from "@/types";

export default function InvoiceDetailPage() {
  const params = useParams<{ id: string }>(); const router = useRouter(); const [invoice, setInvoice] = useState<Invoice>(); const [editing, setEditing] = useState(false);
  useEffect(() => { getInvoice(params.id).then(setInvoice).catch(() => undefined); }, [params.id]);
  if (!invoice) return <WorkspaceShell active="Rechnungen"><div className="panel rounded-2xl p-8 text-sm text-[#8292ae]">Rechnung wird geladen...</div></WorkspaceShell>;
  async function changeStatus(status: InvoiceStatus) { if (!invoice) return; const updated = await updateInvoice(invoice.id, { status, paidAt: status === "paid" ? new Date().toISOString().slice(0, 10) : invoice.paidAt }); if (updated) setInvoice(updated); }
  async function remove() { if (invoice && window.confirm("Rechnung löschen?")) { await deleteInvoice(invoice.id); router.push("/applications"); } }
  return <WorkspaceShell active="Rechnungen" title={`Rechnung ${invoice.invoiceNumber}`}><div className="flex items-center justify-between"><Link href="/applications" className="flex items-center gap-2 text-sm text-[#8292ae]"><ArrowLeft size={17}/>Rechnungen</Link><div className="flex gap-2"><button onClick={() => setEditing(!editing)} className="action"><Pencil size={15}/>{editing ? "Schließen" : "Bearbeiten"}</button><button onClick={remove} aria-label="Rechnung löschen" className="icon-button text-[#ff8f85]"><Trash2 size={16}/></button></div></div>{editing ? <div className="panel mx-auto mt-8 max-w-[1000px] rounded-2xl p-5 md:p-8"><ApplicationForm application={invoice}/></div> : <><div className="mt-9 flex flex-col justify-between gap-5 md:flex-row"><div><p className="text-xs font-semibold uppercase tracking-[.18em] text-[#56c8ff]">{invoiceStatusLabels[invoice.status]}</p><h1 className="mt-3 text-3xl font-semibold text-white">{invoice.invoiceNumber}</h1><p className="mt-2 text-[#b9cbea]">{invoice.customerName}</p><p className="mt-2 whitespace-pre-line text-sm text-[#7185a6]">{invoice.customerAddress}</p></div><label><span className="mb-2 block text-xs text-[#8292ae]">Status</span><select value={invoice.status} onChange={(event) => changeStatus(event.target.value as InvoiceStatus)} className="field">{Object.entries(invoiceStatusLabels).map(([key, label]) => <option key={key} value={key}>{label}</option>)}</select></label></div><section className="panel mt-7 rounded-2xl p-5 md:p-6"><div className="flex flex-wrap justify-between gap-3"><div><p className="text-xs text-[#7185a6]">Rechnungsdatum</p><p className="mt-1 text-sm text-white">{new Date(invoice.issueDate).toLocaleDateString("de-CH")}</p></div><div><p className="text-xs text-[#7185a6]">Fällig am</p><p className="mt-1 text-sm text-white">{new Date(invoice.dueDate).toLocaleDateString("de-CH")}</p></div></div><div className="mt-6 overflow-x-auto"><table className="w-full min-w-[480px] text-sm"><thead className="text-left text-xs text-[#7185a6]"><tr><th className="pb-3">Leistung</th><th className="pb-3 text-right">Menge</th><th className="pb-3 text-right">Preis</th></tr></thead><tbody>{invoice.items.map((item) => <tr key={item.id} className="border-t border-white/10"><td className="py-4 text-white">{item.description}</td><td className="py-4 text-right text-[#8292ae]">{item.quantity}</td><td className="py-4 text-right text-[#8292ae]">{formatCurrency(item.unitPrice)}</td></tr>)}</tbody></table></div><div className="mt-5 border-t border-white/10 pt-4 text-right"><span className="text-xs text-[#8292ae]">Total</span><p className="mt-1 text-2xl font-semibold text-white">{formatCurrency(invoiceTotal(invoice.items))}</p></div>{invoice.notes && <p className="mt-5 border-t border-white/10 pt-4 text-sm text-[#8292ae]">{invoice.notes}</p>}</section></>}</WorkspaceShell>;
}
