"use client";

import { useEffect, useMemo, useState } from "react";
import Link from "next/link";
import { Area, AreaChart, CartesianGrid, ResponsiveContainer, Tooltip, XAxis, YAxis } from "recharts";
import { ArrowUpRight, CircleAlert, CircleCheck, FilePlus2, Pencil, ReceiptText, Target, Wallet, X } from "lucide-react";
import { WorkspaceShell } from "@/components/layout/workspace-shell";
import { getCustomers, getExpenses, getInvoices, getMonthlyGoal, saveMonthlyGoal } from "@/lib/storage";
import { formatCurrency, invoiceStatusLabels, invoiceTotal } from "@/lib/utils";
import type { Customer, Expense, Invoice, MonthlyGoal } from "@/types";

const currentMonth = new Date().toISOString().slice(0, 7);
const monthLabel = (month: string) => new Date(`${month}-01T12:00:00`).toLocaleDateString("de-CH", { month: "long", year: "numeric" });

export default function Dashboard() {
  const [invoices, setInvoices] = useState<Invoice[]>([]); const [expenses, setExpenses] = useState<Expense[]>([]); const [customers, setCustomers] = useState<Customer[]>([]);
  const [selectedMonth, setSelectedMonth] = useState(currentMonth); const [goal, setGoal] = useState<MonthlyGoal>(); const [editingGoal, setEditingGoal] = useState(false); const [goalForm, setGoalForm] = useState({ revenueTarget: "", recurringRevenueTarget: "", expenseBudget: "", notes: "" }); const [error, setError] = useState(""); const [saving, setSaving] = useState(false);

  useEffect(() => { Promise.all([getInvoices(), getExpenses(), getCustomers()]).then(([invoiceData, expenseData, customerData]) => { setInvoices(invoiceData); setExpenses(expenseData); setCustomers(customerData); }).catch(() => setError("Finanzdaten konnten nicht geladen werden.")); }, []);
  useEffect(() => { getMonthlyGoal(selectedMonth).then((data) => { setGoal(data); setGoalForm({ revenueTarget: data?.revenueTarget.toString() ?? "", recurringRevenueTarget: data?.recurringRevenueTarget.toString() ?? "", expenseBudget: data?.expenseBudget.toString() ?? "", notes: data?.notes ?? "" }); }).catch(() => setError("Monatsziel konnte nicht geladen werden.")); }, [selectedMonth]);

  const allMetrics = useMemo(() => { const revenue = invoices.filter(({ status }) => status === "paid").reduce((sum, invoice) => sum + invoiceTotal(invoice.items), 0); const outstanding = invoices.filter(({ status }) => ["sent", "overdue"].includes(status)).reduce((sum, invoice) => sum + invoiceTotal(invoice.items), 0); const costs = expenses.reduce((sum, expense) => sum + expense.amount, 0); return { revenue, outstanding, costs, profit: revenue - costs, overdue: invoices.filter(({ status }) => status === "overdue").length }; }, [expenses, invoices]);
  const monthMetrics = useMemo(() => { const revenue = invoices.filter((invoice) => invoice.status === "paid" && (invoice.paidAt ?? invoice.issueDate).startsWith(selectedMonth)).reduce((sum, invoice) => sum + invoiceTotal(invoice.items), 0); const costs = expenses.filter((expense) => expense.expenseDate.startsWith(selectedMonth)).reduce((sum, expense) => sum + expense.amount, 0); const recurring = customers.reduce((sum, customer) => sum + customer.monthlyRevenue, 0); return { revenue, costs, recurring }; }, [customers, expenses, invoices, selectedMonth]);
  const chartData = Array.from({ length: 6 }, (_, offset) => { const date = new Date(); date.setMonth(date.getMonth() - (5 - offset)); const key = date.toISOString().slice(0, 7); return { month: date.toLocaleDateString("de-CH", { month: "short" }), einnahmen: invoices.filter((invoice) => invoice.status === "paid" && (invoice.paidAt ?? invoice.issueDate).startsWith(key)).reduce((sum, invoice) => sum + invoiceTotal(invoice.items), 0), ausgaben: expenses.filter((expense) => expense.expenseDate.startsWith(key)).reduce((sum, expense) => sum + expense.amount, 0) }; });
  const recent = [...invoices].sort((a, b) => b.updatedAt.localeCompare(a.updatedAt)).slice(0, 5);

  async function submitGoal(event: React.FormEvent) { event.preventDefault(); setSaving(true); try { const saved = await saveMonthlyGoal({ month: selectedMonth, revenueTarget: Number(goalForm.revenueTarget || 0), recurringRevenueTarget: Number(goalForm.recurringRevenueTarget || 0), expenseBudget: Number(goalForm.expenseBudget || 0), notes: goalForm.notes }); setGoal(saved); setEditingGoal(false); } catch { setError("Monatsziel konnte nicht gespeichert werden."); } finally { setSaving(false); } }

  return <WorkspaceShell active="Übersicht" title="Wendico / Übersicht"><div className="page-enter">{error && <div role="alert" className="mb-6 rounded-lg border border-[#fda29b] bg-[#fee4e2] px-4 py-3 text-sm text-[#b42318]">{error}</div>}<div className="flex flex-col justify-between gap-5 sm:flex-row sm:items-end"><div><p className="text-xs font-semibold uppercase tracking-[.14em] text-[var(--primary)]">Finanzen & Planung</p><h1 className="mt-2 text-3xl font-semibold text-[var(--ink)] md:text-4xl">Finanzübersicht</h1><p className="mt-2 text-sm text-[var(--muted)]">Umsatz, Kosten, offene Forderungen und Monatsziele.</p></div><Link href="/applications/new" className="primary flex w-fit items-center gap-2"><FilePlus2 size={16}/>Neue Rechnung</Link></div>
    <section className="mt-7 grid grid-cols-2 gap-3 xl:grid-cols-4"><Metric label="Bezahlter Umsatz" value={formatCurrency(allMetrics.revenue)} icon={CircleCheck}/><Metric label="Offene Forderungen" value={formatCurrency(allMetrics.outstanding)} icon={Wallet}/><Metric label="Ausgaben" value={formatCurrency(allMetrics.costs)} icon={ReceiptText}/><Metric label="Ergebnis" value={formatCurrency(allMetrics.profit)} icon={ArrowUpRight}/></section>
    {allMetrics.overdue > 0 && <div className="mt-4 flex items-center gap-3 rounded-lg border border-[#f79009] bg-[#fffaeb] px-4 py-3 text-sm text-[#93370d]"><CircleAlert size={17}/>{allMetrics.overdue} überfällige Rechnung{allMetrics.overdue === 1 ? "" : "en"} benötigt Aufmerksamkeit.</div>}
    <section className="panel mt-5 rounded-xl p-5"><div className="flex flex-col justify-between gap-4 sm:flex-row sm:items-center"><div className="flex items-center gap-3"><span className="notification-icon"><Target size={18}/></span><div><h2 className="font-semibold text-[var(--ink)]">Monatsziele</h2><p className="text-xs text-[var(--muted)]">Fortschritt für {monthLabel(selectedMonth)}</p></div></div><div className="flex gap-2"><input type="month" value={selectedMonth} onChange={(event) => setSelectedMonth(event.target.value)} className="field w-auto"/><button onClick={() => setEditingGoal((current) => !current)} className="action"><Pencil size={15}/>{goal ? "Bearbeiten" : "Ziele setzen"}</button></div></div>
      {editingGoal && <form onSubmit={submitGoal} className="page-enter mt-5 grid gap-4 border-t border-[var(--line)] pt-5 sm:grid-cols-2 lg:grid-cols-4"><GoalField label="Umsatzziel" value={goalForm.revenueTarget} onChange={(value) => setGoalForm({ ...goalForm, revenueTarget: value })}/><GoalField label="MRR-Ziel" value={goalForm.recurringRevenueTarget} onChange={(value) => setGoalForm({ ...goalForm, recurringRevenueTarget: value })}/><GoalField label="Ausgabenbudget" value={goalForm.expenseBudget} onChange={(value) => setGoalForm({ ...goalForm, expenseBudget: value })}/><label><span className="mb-2 block text-xs font-semibold text-[var(--muted)]">Notiz</span><input value={goalForm.notes} onChange={(event) => setGoalForm({ ...goalForm, notes: event.target.value })} className="field"/></label><div className="flex gap-2 sm:col-span-2 lg:col-span-4"><button disabled={saving} className="primary">{saving ? "Speichert..." : "Monatsziele speichern"}</button><button type="button" onClick={() => setEditingGoal(false)} className="action"><X size={15}/>Abbrechen</button></div></form>}
      {goal ? <div className="mt-5 grid gap-4 border-t border-[var(--line)] pt-5 lg:grid-cols-3"><GoalProgress label="Umsatz" current={monthMetrics.revenue} target={goal.revenueTarget}/><GoalProgress label="Monatlich wiederkehrend" current={monthMetrics.recurring} target={goal.recurringRevenueTarget}/><GoalProgress label="Ausgabenbudget" current={monthMetrics.costs} target={goal.expenseBudget} inverse/></div> : !editingGoal && <button onClick={() => setEditingGoal(true)} className="mt-5 w-full rounded-lg border border-dashed border-[var(--line)] py-8 text-sm font-semibold text-[var(--primary)]">Ziele für {monthLabel(selectedMonth)} festlegen</button>}
      {goal?.notes && <p className="mt-4 text-sm text-[var(--muted)]">{goal.notes}</p>}
    </section>
    <div className="mt-5 grid gap-5 xl:grid-cols-[1.45fr_1fr]"><section className="panel rounded-xl p-5"><h2 className="text-sm font-semibold text-[var(--ink)]">Liquiditätsverlauf</h2><div className="mt-6 h-[280px]"><ResponsiveContainer width="100%" height="100%"><AreaChart data={chartData}><defs><linearGradient id="income" x1="0" y1="0" x2="0" y2="1"><stop offset="0%" stopColor="#3aa981" stopOpacity={.32}/><stop offset="100%" stopColor="#3aa981" stopOpacity={0}/></linearGradient></defs><CartesianGrid vertical={false}/><XAxis dataKey="month"/><YAxis/><Tooltip contentStyle={{ background: "var(--surface)", border: "1px solid var(--line)", borderRadius: 8 }}/><Area type="monotone" dataKey="einnahmen" stroke="#3aa981" fill="url(#income)"/><Area type="monotone" dataKey="ausgaben" stroke="#d92d20" fill="transparent"/></AreaChart></ResponsiveContainer></div></section><section className="panel rounded-xl p-5"><div className="flex justify-between"><h2 className="text-sm font-semibold text-[var(--ink)]">Letzte Rechnungen</h2><Link href="/applications" className="text-xs font-semibold text-[var(--primary)]">Alle anzeigen</Link></div><div className="mt-5 space-y-3">{recent.map((invoice) => <Link key={invoice.id} href={`/applications/${invoice.id}`} className="flex items-center justify-between border-b border-[var(--line)] pb-3"><div><p className="text-sm font-semibold text-[var(--ink)]">{invoice.customerName}</p><p className="mt-1 text-xs text-[var(--muted)]">{invoice.invoiceNumber} · {invoiceStatusLabels[invoice.status]}</p></div><span className="text-sm font-semibold text-[var(--ink)]">{formatCurrency(invoiceTotal(invoice.items), invoice.currency)}</span></Link>)}{!recent.length && <p className="py-10 text-center text-sm text-[var(--muted)]">Noch keine Rechnungen.</p>}</div></section></div>
  </div></WorkspaceShell>;
}

function Metric({ label, value, icon: Icon }: { label: string; value: string; icon: typeof Wallet }) { return <div className="panel card-lift rounded-xl p-4 md:p-5"><div className="flex items-start justify-between"><p className="text-xs text-[var(--muted)]">{label}</p><Icon size={17} className="text-[var(--primary)]"/></div><p className="mt-4 text-xl font-semibold text-[var(--ink)] md:text-2xl">{value}</p></div>; }
function GoalField({ label, value, onChange }: { label: string; value: string; onChange: (value: string) => void }) { return <label><span className="mb-2 block text-xs font-semibold text-[var(--muted)]">{label} (CHF)</span><input type="number" min="0" step="100" value={value} onChange={(event) => onChange(event.target.value)} className="field"/></label>; }
function GoalProgress({ label, current, target, inverse = false }: { label: string; current: number; target: number; inverse?: boolean }) { const percentage = target > 0 ? Math.round(current / target * 100) : 0; const width = Math.min(percentage, 100); const healthy = inverse ? current <= target : current >= target; return <div className="rounded-lg bg-[var(--surface-soft)] p-4"><div className="flex items-start justify-between gap-3"><div><p className="text-xs font-semibold text-[var(--muted)]">{label}</p><p className="mt-1 text-lg font-semibold text-[var(--ink)]">{formatCurrency(current)}</p></div><span className={`rounded-md px-2 py-1 text-xs font-semibold ${healthy ? "bg-[#d1fadf] text-[#05603a]" : "bg-[var(--accent)] text-[var(--primary)]"}`}>{percentage}%</span></div><div className="mt-3 h-2 overflow-hidden rounded-full bg-[var(--line)]"><div className={`h-full rounded-full transition-all duration-500 ${inverse && current > target ? "bg-[#d92d20]" : "bg-[var(--primary)]"}`} style={{ width: `${width}%` }}/></div><p className="mt-2 text-xs text-[var(--muted)]">{inverse ? `Budget ${formatCurrency(target)}` : `Ziel ${formatCurrency(target)}`}</p></div>; }
